# HMPPS Java Base Image (Distroless Java 21)

FROM debian:13 AS prep

ARG APP_UID=2000
ARG APP_GID=2000

# Create app user/group and RDS cert path in a full userland stage.
RUN groupadd --gid ${APP_GID} --system appgroup && \
    useradd --uid ${APP_UID} --system --gid ${APP_GID} --shell /usr/sbin/nologin appuser
RUN install -d -o appuser -g appgroup /home/appuser/.postgresql
ADD https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem /home/appuser/.postgresql/root.crt
RUN chown appuser:appgroup /home/appuser/.postgresql/root.crt && \
    chmod 0644 /home/appuser/.postgresql/root.crt

FROM gcr.io/distroless/java21-debian13:nonroot AS runtime

ARG APP_UID=2000
ARG APP_GID=2000

LABEL org.opencontainers.image.title="HMPPS Java Base Image (Distroless Java 21)"
LABEL org.opencontainers.image.description="Distroless runtime image for Java 21 applications in HMPPS"
LABEL org.opencontainers.image.source="https://github.com/ministryofjustice/hmpps-base-container-images"
LABEL org.opencontainers.image.vendor="Ministry of Justice"
LABEL hmpps.java.base_variant="distroless"
LABEL org.opencontainers.image.base.name="gcr.io/distroless/java21-debian13:nonroot"

WORKDIR /app

# Sensible JVM defaults for containers
ENV TZ="Europe/London"
ENV JAVA_TOOL_OPTIONS="-XX:+ExitOnOutOfMemoryError -XX:MaxRAMPercentage=50.0"

COPY --from=prep --chown=${APP_UID}:${APP_GID} /home/appuser/.postgresql/root.crt /home/appuser/.postgresql/root.crt

USER ${APP_UID}:${APP_GID}
